### ISSUE TITLE
Possible (but strongly recommended) ToDo's

### ISSUE THREAD

**Issue by bommezijn** [bommezijn/frontend-data#6]
Things I would like to do before I hand this project in.

- [ ] Create another chart, or two. (Pie chart, scatterplot, ya know)
- [x] Add update function so I can apply for a grading.
- [x] FIX DOCUMENTATION..
  - [ ] Write documentation about d3.js and the pattern `enter()`, `update()`, and `exit()`
  - [ ] Write in my diary.
